UM_METRO_E_SESSENTA = 1.60
UM_METRO_E_SETENTA = 1.70

SETENTA_E_DOIS_QUILOS = 72
SETENTA_E_SEIS_QUILOS = 76
CINQUENTA_E_SETE_QUILOS = 57
CENTO_E_QUARENTA_QUILOS = 140
SETENTA_E_CINCO_QUILOS = 75

IMC_DEZENOVE_PONTO_SETENTA_E_DOIS = 19.72
IMC_VINTE_E_QUATRO_PONTO_NOVENTA_E_UM = 24.91
IMC_VINTE_E_SEIS_PONTO_TRES = 26.3






